### PR TITLE
Grasshopper_Toolkit: Issue 384 - Add hints and tree access to property value of SetProperty

### LINKED ISSUE #350: Grasshopper_Toolkit: Param_ScriptVariables' menu has a `List` entry that does breaks the backend BHoM method
`SetProperty` component provides an option to input a list (screen below). However, after clicking the option, the component crashes with the following error:

_1. This component failed to run properly. Inputs cannot be collected properly.
GetData() can only be called on a parameter with access set to GH_ParamAccess.item_

image

### LINKED ISSUE #384: Grasshopper_Toolkit: SetProperty does not work for List inputs
This is the first half of https://github.com/BHoM/Grasshopper_Toolkit/issues/350
FYI @pawelbaran

### PR DESCRIPTION
**Pull request by epignatelli**
Depends on: https://github.com/BHoM/BHoM_UI/pull/116

   
### Issues addressed by this PR

Closes #384 
Closes #350 
Opens #372 

I left some messages on the code itself to make it easier for the reviewers to track the changes.
To summarise:
- The `SetPropertyComponent` requires the method `CreateCustom.OnGrasshopperUpdates` exactly as it is. The method has now been migrated to the `CallerComponent` exactly as it is. The `Explode` component also overwrites that method. 
- The `SetProperty` now contains `Hints` and `TreeAccess` exactly like the `CreateCustomComponent` - also works with the same logic.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Eo5nuf2lHsJKolP8-gDFP7kBavPMdolrSTc2pnjhX5ebxw?e=Yg8K8l

### CODE REVIEW

File: Grasshopper_Engine/Query/Type.cs [hunk 1]
```diff
@@ -56,7 +56,7 @@ public static Type Type(this IGH_Param param, Caller caller = null)
         public static Type Type(this IGH_TypeHint hint, GH_ParamAccess access)
         {
             if (hint == null)
-                return typeof(object);
+                return Type<object>(access);
```
Comment (epignatelli) [inline Grasshopper_Engine/Query/Type.cs]: This guarantees that `List<object>` is treated the same as any other type

File: Grasshopper_Engine/Query/Type.cs [hunk 2]
```diff
@@ -44,8 +44,8 @@ public static Type Type(this IGH_Param param, Caller caller = null)
             if (param is Param_ScriptVariable)
                 return Type(((Param_ScriptVariable)param).TypeHint, param.Access);
 
-            else if (caller != null && caller is CreateCustomCaller)
-                return ((CreateCustomCaller)caller).GetParam(param.NickName).DataType;
+            else if (caller != null)
+                return (caller.InputParams.Find(x => x.Name == param.NickName))?.DataType;
```
Comment (epignatelli) [inline Grasshopper_Engine/Query/Type.cs]: There is no need to calculate the type. Type is known if the `Caller` is set. 
Switch to `Find`.

File: Grasshopper_UI/2.1/Components/Engine/SetProperty.cs [hunk 3]
```diff
@@ -39,6 +37,25 @@ public class SetPropertyComponent : CallerComponent
...
+        /**** Constructors                      ****/
+        /*******************************************/
+
+        public SetPropertyComponent() : base()
+        {
+            this.Params.ParameterChanged += OnGrasshopperUpdates;
+            if (Params.Input.Count > 2)
+            {
+                Param_ScriptVariable paramScript = Params.Input[2] as Param_ScriptVariable;
+                if (paramScript != null)
```
Comment (epignatelli) [inline Grasshopper_UI/2.1/Components/Engine/SetProperty.cs]: This allows `SetProperty` to have typehints and tree access

File: Grasshopper_UI/2.1/Components/UI/UpdateVersion.cs [hunk 4]
```diff
@@ -389,7 +389,7 @@ private static bool ReplaceObsolete(GH_Document doc, CreateCustomObject componen
         {
             CreateCustomComponent newComp = new CreateCustomComponent();
             CreateCustomCaller caller = newComp.Caller as CreateCustomCaller;
-            caller.SetInputs(component.Params.Input.Select(x => x.NickName).ToList());
+            caller.SetInputParams(component.Params.Input.Select(x => x.NickName).ToList());
```
Comment (epignatelli) [inline Grasshopper_UI/2.1/Components/UI/UpdateVersion.cs]: Aligns with the `MethodCaller.SetInputParams`

File: Grasshopper_UI/2.1/Components/oM/CreateCustom.cs [hunk 5]
```diff
@@ -50,38 +49,6 @@ public CreateCustomComponent() : base()
         }
 
 
-        /*******************************************/
-        /**** Public Methods                    ****/
-        /*******************************************/
-
-        public void OnGrasshopperUpdates(object sender, GH_ParamServerEventArgs e)
```
Comment (epignatelli) [inline Grasshopper_UI/2.1/Components/oM/CreateCustom.cs]: This is centralised in `Caller` now, since it is used by all the components.

File: Grasshopper_UI/2.1/Templates/CallerComponent.cs [hunk 6]
```diff
@@ -116,9 +119,34 @@ public virtual void OnSourceCodeClick(object sender = null, object e = null)
 
         /*******************************************/
 
+        public virtual void OnGrasshopperUpdates(object sender, GH_ParamServerEventArgs e)
```
Comment (epignatelli) [inline Grasshopper_UI/2.1/Templates/CallerComponent.cs]: Migrated from `CreateCustom` as it is used also by others - e.g. `SetProperty`

**Comment by FraserGreenroyd** [comment]
Cannot be merged until Dynamo Toolkit is also reviewed - from BHoM call.

**Comment by epignatelli** [comment]
https://github.com/BHoM/Dynamo_Toolkit/pull/158 has now been approved.
Targeting the merge on Monday.
